In [13]:
#babbule sort
import numpy as np
def bubble(arr ,n):
    for i in range(n-1):
        for j in range(n-i-1):
            if arr[j] > arr[j+1]:
                arr[j] , arr[j+1] =arr[j+1] , arr[j]      
    return arr
#function calling
arr=np.array([5,4 , 7 , 6 , 1])
bubble(arr ,len(arr))
print(arr)               

[1 4 5 6 7]


In [19]:
#babbule sort
def bubble(arr ,n):
    for i in range(n-1):
        for j in range(n-i-1):
            if arr[j] > arr[j+1]:
               swap(arr , j ,j+1)
#function calling
arr=np.array([5,4,3,2,1,0])
bubble(arr ,len(arr))
print(arr) 

[0 1 2 3 4 5]


In [20]:
#babbule sort
import numpy as np
def bubble(arr ,n):
    for i in range(n-1):
        for j in range(n-i-1):
            if arr[j] > arr[j+1]:
                temp=arr[j]
                arr[j] = arr[j+1]
                arr[j] =temp
#function calling
arr=np.array([5,4,3,2,1,0])
bubble(arr ,len(arr))
print(arr)

[5 4 3 2 1 0]


In [24]:
#optimize solution for best case
def Bubble(arr , n):
    for i in range(n-1):
        flag=False
        for j in range(n-i-1):
            if arr[j] > arr[j+1]:
                arr[j] , arr[j+1] = arr[j+1] , arr[j]
                flag=True
        if flag==False:
            return arr
#function calling
arr=np.array([2 , 1 , 3 , 6 , 9])
Bubble(arr ,len(arr))
print(arr)

[1 2 3 6 9]


In [2]:
#bubble sort reverse order
import numpy as np
def bubble_reverse(arr):     #[ 4 , 2 , 1 , 5, ]
    n=len(arr)-1
    for i in range(n):
        for j in range(0 , n-i):
            if arr[j+1] > arr[j]:
                arr[j] , arr[j+1] = arr[j+1] , arr[j]
arr=np.array([2 , 1 , 3 , 6 , 9])
bubble_reverse(arr)
print(arr)

[9 6 3 2 1]
